version: '3'

services:
  yii2-mysql:
    container_name: yii2-mysql
    image: mysql/mysql-server:${MYSQL_VERSION}
    env_file:
      - .env
    volumes:
      - ./conf/my.cnf:/etc/my.cnf
      - ./data:/var/lib/mysql
    restart: unless-stopped

  yii2:
    container_name: yii2
    image: bridennis/anpx:8.2
    env_file:
      - .env
    volumes:
      - ./www:/var/www/html
      - ./conf/:/usr/etc/
      - ./data:/var/lib/mysql
    ports:
      - "80:80"
    restart: always
    depends_on:
      - yii2-mysql
    command: /bin/sh -c "/usr/sbin/php-fpm
      && /var/www/html/infra/init.sh
      && cp /usr/etc/nginx.conf /usr/local/nginx/conf/default.conf
      && sed -i "s/_MYSQL_DATABASE/$MYSQL_DATABASE/g" /usr/local/nginx/conf/default.conf
      && sed -i "s/_MYSQL_USER/$MYSQL_USER/g" /usr/local/nginx/conf/default.conf
      && sed -i "s/_MYSQL_PASSWORD/$MYSQL_PASSWORD/g" /usr/local/nginx/conf/default.conf
      && /usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/default.conf"
